In [185]:
import pandas as pd

In [186]:
lp = pd.read_csv("laptopPrice.csv")

In [187]:
lp

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [188]:
lp.isnull().sum()  # sum of all null values

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [189]:
lp.duplicated().sum()  # sum of all duplicate values

np.int64(21)

In [190]:
lp

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [191]:
lp.drop_duplicates(inplace=True) #used to save the dataset without storing it into new variable

In [192]:
lp

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [193]:
lp.duplicated().sum()  # sum of all duplicate values

np.int64(0)

In [194]:
lp.dropna(inplace=True)

In [195]:
lp

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [196]:
# fill null value
lp.fillna(0)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [197]:
lp.dtypes

brand                object
processor_brand      object
processor_name       object
processor_gnrtn      object
ram_gb               object
ram_type             object
ssd                  object
hdd                  object
os                   object
os_bit               object
graphic_card_gb      object
weight               object
warranty             object
Touchscreen          object
msoffice             object
Price                 int64
rating               object
Number of Ratings     int64
Number of Reviews     int64
dtype: object

In [198]:
lp = lp.drop(['Touchscreen', 'msoffice', 'warranty'], axis=1)

In [199]:
lp

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,57490,4 stars,18,4

In [200]:
for col in [
    "brand",
    "processor_brand",
    "processor_name",
    "processor_gnrtn",
    "ram_gb",
    "ram_type",
    "ssd",
    "hdd",
    "os",
    "os_bit",
    "graphic_card_gb",
    "weight",
    "rating",
]:
    print(f"Unique values in {col}: {lp[col].unique()}")

Unique values in brand: ['ASUS' 'Lenovo' 'acer' 'Avita' 'HP' 'DELL' 'MSI' 'APPLE']
Unique values in processor_brand: ['Intel' 'AMD' 'M1']
Unique values in processor_name: ['Core i3' 'Core i5' 'Celeron Dual' 'Ryzen 5' 'Core i7' 'Core i9' 'M1'
 'Pentium Quad' 'Ryzen 3' 'Ryzen 7' 'Ryzen 9']
Unique values in processor_gnrtn: ['10th' 'Not Available' '11th' '7th' '8th' '9th' '4th' '12th']
Unique values in ram_gb: ['4 GB' '8 GB' '16 GB' '32 GB']
Unique values in ram_type: ['DDR4' 'LPDDR4' 'LPDDR4X' 'DDR5' 'DDR3' 'LPDDR3']
Unique values in ssd: ['0 GB' '512 GB' '256 GB' '128 GB' '1024 GB' '2048 GB' '3072 GB']
Unique values in hdd: ['1024 GB' '0 GB' '512 GB' '2048 GB']
Unique values in os: ['Windows' 'DOS' 'Mac']
Unique values in os_bit: ['64-bit' '32-bit']
Unique values in graphic_card_gb: ['0 GB' '2 GB' '4 GB' '6 GB' '8 GB']
Unique values in weight: ['Casual' 'ThinNlight' 'Gaming']
Unique values in rating: ['2 stars' '3 stars' '4 stars' '5 stars' '1 star']

# Maping

In [201]:
brand_map = {
    "ASUS": 1,
    "Lenovo": 2,
    "acer": 3,
    "Avita": 4,
    "HP": 5,
    "DELL": 6,
    "MSI": 7,
    "APPLE": 8,
}
processor_brand_map = {"Intel": 1, "AMD": 2, "M1": 3}
processor_name_map = {
    "M1": 1,
    "Celeron Dual": 2,
    "Core i3": 3,
    "Core i5": 5,
    "Core i7": 7,
    "Core i9": 9,
    "Pentium Quad": 4,
    "Ryzen 3": 33,
    "Ryzen 5": 55,
    "Ryzen 7": 77,
    "Ryzen 9": 99,
}
processor_gnrtn_map = {
    "Not Available": 0,
    "4th": 4,
    "7th": 7,
    "8th": 8,
    "9th": 9,
    "10th": 10,
    "11th": 11,
    "12th": 12,
}
ram_gb_map = {"4 GB": 4, "8 GB": 8, "16 GB": 16, "32 GB": 32}
ram_type_map = {"DDR4": 44, "LPDDR4": 244, "LPDDR4X": 2447, "DDR5": 45, "DDR3": 43, "LPDDR3": 243}
ssd_map = {
    "0 GB": 0,
    "128 GB": 128,
    "256 GB": 256,
    "512 GB": 512,
    "1024 GB": 1024,
    "2048 GB": 2048,
    "3072 GB": 3072,
}
hdd_map = {"0 GB": 0, "512 GB": 512, "1024 GB": 1024, "2048 GB": 2048}
os_map = {"Windows": 1, "DOS": 2, "Mac": 3}
os_bit_map = {"64-bit": 64, "32-bit": 32}
graphic_card_gb_map = {"0 GB": 0, "2 GB": 2, "4 GB": 4, "6 GB": 6, "8 GB": 8}
weight_map = {"Casual": 1, "ThinNlight": 2, "Gaming": 3}
rating_map = {"1 star": 1, "2 stars": 2, "3 stars": 3, "4 stars": 4, "5 stars": 5}

mapping

In [202]:
lp["brand"] = lp["brand"].map(brand_map)
lp["processor_brand"] = lp["processor_brand"].map(processor_brand_map)
lp["processor_name"] = lp["processor_name"].map(processor_name_map)
lp["processor_gnrtn"] = lp["processor_gnrtn"].map(processor_gnrtn_map)
lp["ram_gb"] = lp["ram_gb"].map(ram_gb_map)
lp["ram_type"] = lp["ram_type"].map(ram_type_map)
lp["ssd"] = lp["ssd"].map(ssd_map)
lp["hdd"] = lp["hdd"].map(hdd_map)
lp["os"] = lp["os"].map(os_map)
lp["os_bit"] = lp["os_bit"].map(os_bit_map)
lp["graphic_card_gb"] = lp["graphic_card_gb"].map(graphic_card_gb_map)
lp["weight"] = lp["weight"].map(weight_map)
lp["rating"] = lp["rating"].map(rating_map)

In [203]:
lp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              802 non-null    int64
 1   processor_brand    802 non-null    int64
 2   processor_name     802 non-null    int64
 3   processor_gnrtn    802 non-null    int64
 4   ram_gb             802 non-null    int64
 5   ram_type           802 non-null    int64
 6   ssd                802 non-null    int64
 7   hdd                802 non-null    int64
 8   os                 802 non-null    int64
 9   os_bit             802 non-null    int64
 10  graphic_card_gb    802 non-null    int64
 11  weight             802 non-null    int64
 12  Price              802 non-null    int64
 13  rating             802 non-null    int64
 14  Number of Ratings  802 non-null    int64
 15  Number of Reviews  802 non-null    int64
dtypes: int64(16)
memory usage: 106.5 KB

In [204]:
lp.head(30)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,Price,rating,Number of Ratings,Number of Reviews
0,1,1,3,10,4,44,0,1024,1,64,0,1,34649,2,3,0
1,2,1,3,10,4,44,0,1024,1,64,0,1,38999,3,65,5
2,2,1,3,10,4,44,0,1024,1,64,0,1,39999,3,8,1
3,1,1,5,10,8,44,512,0,1,32,2,1,69990,3,0,0
4,1,1,2,0,4,44,0,512,1,64,0,1,26990,3,0,0
5,1,1,2,0,4,44,0,512,1,64,0,1,22990,3,0,0
6,1,1,2,0,4,44,0,512,1,32,0,1,21990,3,31,3
7,1,1,5,10,8,44,0,1024,1,32,2,1,58799,3,0,0
8,2,1,5,10,4,44,0,1024,1,32,0,1,49999,3,0,0
9,3,2,55,10,4,44,0,512,1,32,4,1,59990,4,1946,240
10,3,2,55,10,4,44,0,512,1,32,6,1,93700,4,259,47
11,3,2,55,10,4,44,0,512,1,32,4,1,72990,4,425,67
12,4,1,2,0,4,44,0,512,1,64,0,1,17490,3,1120,196
14,1,1,3,11,4,44,256,0,1,64,0,1,35990,3,0,0
15,5,1,3,11,8,44,256,0,1,64,0,1,56490,3,0,0
16,5,1,5,11,8,44,256,0,1,64,0,1,65390,3,0,0
17,2,1,2,0,4,44,256,0,1,64,0,2,31999,4,286,19
18,5,1,2,0,8,44,256,0,1,64,0,2,32490,4,58,6
19,2,1,2,0,4,44,256,0,1,64,0,2,31799,3,0,0
20,1,1,2,0,4,44,256,0,1,64,0,1,29890,4,7,0
21,1,1,2,0,4,44,0,1024,1,64,0,1,23990,3,15279,1947
22,5,1,3,7,4,44,0,1024,1,64,0,1,32955,4,311,27
23,5,1,5,7,4,44,0,1024,1,32,2,1,46200,4,47,7
24,1,1,3,11,4,44,256,0,1,64,0,2,34429,4,37,6
25,2,1,3,10,8,44,256,0,1,32,0,2,37990,4,2080,235
26,1,1,3,11,4,44,256,0,1,32,0,1,35990,4,1479,181
27,1,1,3,10,8,44,256,0,1,64,0,2,33980,4,67,3
28,5,1,3,11,8,44,256,0,1,64,0,2,39990,4,273,30
29,6,1,3,10,8,44,256,0,1,64,0,2,39490,4,1267,171
30,5,1,3,11,8,44,256,0,1,64,0,1,53990,4,14,0

In [205]:
import sklearn

In [206]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [207]:
# obj
encoder = LabelEncoder()

In [208]:
output = encoder.fit_transform(lp["brand"])

In [209]:
output.shape

(802,)

In [210]:
output

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 2, 2, 2, 3, 0, 4, 4, 1, 4, 1, 0, 0, 4,
       4, 0, 1, 0, 0, 4, 5, 4, 2, 0, 0, 1, 1, 5, 0, 1, 5, 5, 1, 0, 1, 5,
       1, 5, 5, 5, 5, 1, 0, 1, 1, 1, 1, 4, 6, 5, 0, 1, 1, 5, 2, 5, 0, 1,
       0, 1, 0, 1, 4, 1, 0, 4, 5, 5, 1, 5, 1, 0, 5, 0, 0, 4, 0, 4, 4, 0,
       0, 0, 0, 0, 1, 5, 4, 4, 0, 6, 4, 6, 0, 1, 0, 4, 4, 0, 5, 4, 5, 5,
       0, 1, 4, 4, 4, 0, 4, 0, 0, 0, 0, 4, 4, 5, 1, 5, 4, 0, 1, 5, 5, 5,
       4, 0, 5, 1, 0, 0, 5, 5, 1, 4, 4, 5, 4, 0, 4, 0, 0, 5, 0, 4, 5, 0,
       5, 4, 1, 0, 2, 5, 0, 5, 0, 0, 0, 5, 0, 0, 5, 5, 5, 0, 5, 2, 5, 5,
       5, 0, 5, 5, 5, 5, 5, 5, 0, 0, 4, 4, 1, 1, 1, 1, 2, 2, 2, 0, 5, 5,
       4, 4, 1, 4, 1, 2, 0, 5, 2, 4, 2, 0, 1, 4, 4, 1, 4, 0, 1, 1, 1, 1,
       0, 1, 2, 1, 0, 0, 1, 0, 6, 0, 6, 0, 5, 5, 1, 0, 4, 0, 4, 4, 2, 5,
       0, 0, 5, 5, 0, 6, 4, 0, 1, 1, 4, 2, 0, 4, 5, 0, 4, 0, 1, 4, 5, 5,
       0, 1, 1, 5, 1, 0, 1, 5, 6, 0, 1, 5, 1, 1, 0, 4, 1, 1, 4, 5, 1, 1,
       0, 6, 5, 1, 0, 5, 5, 5, 0, 5, 6, 0, 6, 5, 0, 5, 5, 5, 7, 7, 6, 6,
       1, 1, 4, 4, 1, 1, 2, 0, 6, 4, 1, 1, 2, 4, 0, 2, 0, 4, 1, 5, 4, 5,
       5, 1, 0, 4, 0, 1, 5, 1, 0, 6, 0, 1, 5, 4, 0, 1, 0, 1, 5, 5, 1, 5,
       5, 0, 5, 4, 0, 4, 5, 2, 1, 5, 0, 4, 6, 5, 5, 5, 5, 4, 5, 6, 0, 0,
       0, 0, 1, 1, 5, 0, 1, 3, 5, 5, 0, 3, 0, 1, 4, 3, 4, 1, 0, 1, 0, 0,
       0, 7, 7, 0, 0, 0, 5, 1, 1, 1, 2, 2, 5, 2, 0, 6, 1, 1, 1, 2, 5, 0,
       2, 0, 0, 5, 0, 6, 6, 6, 4, 4, 4, 2, 4, 2, 0, 0, 2, 0, 5, 2, 2, 5,
       0, 1, 0, 0, 1, 5, 0, 0, 5, 4, 5, 1, 0, 5, 1, 0, 0, 5, 5, 5, 5, 5,
       1, 0, 5, 2, 5, 6, 5, 3, 0, 0, 6, 1, 1, 1, 0, 1, 4, 0, 1, 6, 4, 5,
       0, 4, 6, 4, 1, 6, 6, 6, 4, 0, 5, 0, 6, 4, 4, 5, 6, 1, 1, 5, 4, 6,
       0, 0, 1, 0, 1, 1, 4, 1, 1, 0, 6, 6, 0, 0, 0, 4, 0, 6, 0, 0, 5, 4,
       6, 1, 0, 6, 4, 4, 1, 6, 4, 6, 2, 4, 5, 0, 4, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 4, 3, 1, 4, 4, 1, 2, 0, 0, 4, 6, 0, 0, 2, 6, 0, 2, 2, 2,
       2, 6, 0, 0, 0, 1, 0, 6, 6, 6, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 4, 0, 2, 5, 0, 5, 0, 0, 0, 0, 4,
       0, 5, 5, 5, 0, 5, 0, 0, 2, 4, 4, 2, 4, 5, 5, 5, 4, 5, 5, 5, 5, 4,
       1, 5, 4, 5, 5, 5, 5, 6, 5, 4, 1, 1, 4, 6, 4, 2, 1, 2, 1, 6, 5, 4,
       1, 4, 5, 4, 4, 0, 0, 4, 0, 4, 4, 4, 4, 0, 5, 5, 4, 5, 5, 1, 0, 4,
       1, 4, 0, 4, 2, 4, 1, 5, 6, 2, 4, 2, 4, 0, 2, 0, 1, 4, 5, 4, 0, 4,
       4, 5, 1, 4, 5, 0, 1, 0, 0, 1, 4, 5, 0, 4, 0, 0, 0, 0, 0, 1, 0, 5,
       0, 0, 0, 1, 0, 6, 1, 1, 4, 0, 1, 4, 0, 1, 2, 0, 4, 5, 1, 1, 1, 0,
       5, 4, 1, 4, 4, 6, 0, 4, 4, 0, 0, 2, 0, 4, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 4, 2, 2, 1, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [211]:
lp["brand"] = output

In [212]:
lp

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,Price,rating,Number of Ratings,Number of Reviews
0,0,1,3,10,4,44,0,1024,1,64,0,1,34649,2,3,0
1,1,1,3,10,4,44,0,1024,1,64,0,1,38999,3,65,5
2,1,1,3,10,4,44,0,1024,1,64,0,1,39999,3,8,1
3,0,1,5,10,8,44,512,0,1,32,2,1,69990,3,0,0
4,0,1,2,0,4,44,0,512,1,64,0,1,26990,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,2,99,0,4,44,1024,0,1,64,0,1,135990,3,0,0
819,0,2,99,0,4,44,1024,0,1,64,0,1,144990,3,0,0
820,0,2,99,0,4,44,1024,0,1,64,4,1,149990,3,0,0
821,0,2,99,0,4,44,1024,0,1,64,4,1,142990,3,0,0
822,1,2,55,10,8,44,512,0,2,64,0,2,57490,4,18,4

In [213]:
lp.dtypes

brand                int64
processor_brand      int64
processor_name       int64
processor_gnrtn      int64
ram_gb               int64
ram_type             int64
ssd                  int64
hdd                  int64
os                   int64
os_bit               int64
graphic_card_gb      int64
weight               int64
Price                int64
rating               int64
Number of Ratings    int64
Number of Reviews    int64
dtype: object

In [214]:
x = lp.drop(["Price"], axis=1)
y = lp[["Price"]]
y  # dependent

      Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
818  135990
819  144990
820  149990
821  142990
822   57490

[802 rows x 1 columns]

In [215]:
x  # independent var

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,rating,Number of Ratings,Number of Reviews
0,0,1,3,10,4,44,0,1024,1,64,0,1,2,3,0
1,1,1,3,10,4,44,0,1024,1,64,0,1,3,65,5
2,1,1,3,10,4,44,0,1024,1,64,0,1,3,8,1
3,0,1,5,10,8,44,512,0,1,32,2,1,3,0,0
4,0,1,2,0,4,44,0,512,1,64,0,1,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,2,99,0,4,44,1024,0,1,64,0,1,3,0,0
819,0,2,99,0,4,44,1024,0,1,64,0,1,3,0,0
820,0,2,99,0,4,44,1024,0,1,64,4,1,3,0,0
821,0,2,99,0,4,44,1024,0,1,64,4,1,3,0,0
822,1,2,55,10,8,44,512,0,2,64,0,2,4,18,4

In [216]:
from sklearn.model_selection import train_test_split

In [217]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)  # testsize how much data u want to keep for testing

In [218]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((641, 15), (161, 15), (641, 1), (161, 1))

In [219]:
x_train.head()
x_train.shape

(641, 15)

In [220]:
y_train.head()
y_train.shape

(641, 1)

In [221]:
x_test

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,rating,Number of Ratings,Number of Reviews
196,2,1,5,0,8,45,0,512,1,32,4,1,4,10966,1185
299,0,1,5,11,8,2447,512,0,1,32,0,1,4,76,14
171,5,1,3,10,8,44,256,1024,1,64,0,2,5,7,5
537,4,1,7,10,16,44,1024,0,1,64,6,1,4,17,4
551,6,1,7,11,16,44,1024,0,1,64,8,1,4,14,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,0,1,5,11,8,2447,512,0,1,64,0,1,3,0,0
361,4,1,5,10,8,44,512,0,1,64,0,1,5,2,1
446,5,1,5,11,8,44,256,1024,1,64,0,1,4,47,0
767,1,2,77,0,4,44,512,0,1,64,4,1,3,0,0
529,1,1,7,11,16,44,512,0,1,32,0,1,3,0,0

In [222]:
y_test

      Price
196   50990
299   72990
171   41490
537  144690
551  129990
..      ...
368  114990
361  126000
446   57990
767  106990
529  110999

[161 rows x 1 columns]

# linear regresion